[book]
authors = ["redsolver"]
language = "en"
multilingual = false
src = "src"
title = "S5 Network Docs"

[output.html]
smart-punctuation = true
site-url = "/"
git-repository-url = "https://github.com/s5-dev/docs/"
edit-url-template = "https://github.com/s5-dev/docs/edit/main/{path}"

[output.html.fold]
enable = true
level = 0

[output.html.playground]
editable = true
